- name: Clear phones folder
  run: rm -rf phones/*.jpg

- name: Download Wikipedia images
  run: node im1.mjs

- name: Commit changes
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add phones
    git commit -m "Redownload all Nokia images" || echo "No changes"
    git push