name: Download Phone Images

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: node im1.mjs

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add phones
          git commit -m "Add phone images" || echo "No changes"
          git push